name: CMake

runs:
  using: composite
  steps:
    - name: Create build directory
      run: mkdir build
      shell: bash
    - name: Configure
      run: |
        cmake -LA .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${CMAKE_OPTS}
      shell: bash
      working-directory: build

